In [9]:
import pandas as pd
import numpy as np

df = pd.read_csv("../../data/car_fuel_efficiency_2026.csv")

In [8]:
## Q1. Pandas version
pd.__version__

'3.0.6'

In [10]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [12]:
## Q2. Records Count
df.shape

(10000, 11)

In [13]:
## Q3. Fuel types
df["fuel_type"].nunique()

3

In [18]:
## Q4. Missing Values
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [20]:
## Q5. Maximum Fuel Efficiency for Asia
asia_cars = df[df["origin"] == "Asia"]
asia_cars["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [21]:
## Q6. Horsepower Median
median_before = df["horsepower"].median()
median_before

np.float64(254.0)

In [22]:
mode_hp = df["horsepower"].mode()
mode_hp

0    252.0
Name: horsepower, dtype: float64

In [23]:
df_filled = df.copy()

In [24]:
df_filled["horsepower"] = df_filled["horsepower"].fillna(mode_hp)

In [25]:
median_after = df_filled["horsepower"].median()
median_after

np.float64(254.0)

In [26]:
median_before, median_after

(np.float64(254.0), np.float64(254.0))

In [27]:
## Q7.
asia_cars = df[df["origin"] == "Asia"]

In [28]:
asia_selected = asia_cars[["vehicle_weight", "model_year"]]

In [29]:
asia_selected = asia_selected.head(7)
asia_selected

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [30]:
x = asia_selected.to_numpy()
x

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [31]:
x.shape

(7, 2)

In [33]:
XTX = x.T @ x
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [35]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [36]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [38]:
w = XTX_inv @ x.T @ y
w

array([0.13644777, 0.2327492 ])

In [39]:
w.sum()

np.float64(0.36919696904925203)